# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 851f3a2c9dd5d4a5c79a9cf3bc7a4f13b5b95dcd3d3e61701b9acb5a191bd9bf453f9d8fc837a916c567db001c523b040745169024e21e84ef5d57a757092777

test:
  secret_key_base: 49b0fa5caa909da1db87938682bd10f02f7b4ed33cd74958ead950cfc95d4b9765047be0558d4926f6b51c8d646ec20f998a2accaecc04fa24f6e28d00e90669

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
